#numbers = (10, 20, 30, 40, 50)Add 60 to the end,Replace 30 with 35.
numbers=(10,20,30,40)
numbers=list(numbers)
print(numbers)
print(type(numbers))
numbers.append(60)
print(numbers)
numbers[2]=35
print(numbers)
numbers=tuple(numbers)
print(numbers)
print(type(numbers))

#values = (15, 5, 30, 25, 10) arrange the elements in ascending order.
values=(15,5,30,25,10)
values=list(values)
print(values)
print(type(values))
values.sort()
print(values)
values=tuple(values)
print(values)
print(type(values))

 #fruits = ("apple", "banana", "cherry", "banana", "mango", "banana")
#Count occurrences of "banana",Remove all occurrences of "banana".
fruits=("apple", "banana", "cherry", "banana", "mango", "banana")
occurrence=fruits.count("banana")
print(occurrence)
fruits=list(fruits)
print(fruits)
fruits.pop()
print(fruits)
fruits.pop(-2)
print(fruits)
fruits.pop(1)
print(fruits)
#names = ("Alice", "Bob", "Charlie", "David") Reverse the order of elements using sort method.
names=("Alice", "Bob", "Charlie", "David")
names=list(names)
print(names)
print(type(names))
names.reverse()
print(names)
names=tuple(names)
print(names)
print(type(names))


#colors = ("red", "blue", "green")add "yellow" at index 1,Extend with ["purple", "orange"]
colors=("red", "blue", "green")
colors=list(colors)
print(colors)
colors.insert(1, "yellow")
print(colors)
colors.extend(["purple", "orange"])
print(colors)
